spring:
  application:
    name: dubbo-demo
nacos:
  host: autopai-cloud-nacos-local
  port: 8848
dubbo:
  application:
    name: dubbo-demo
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://${nacos.host}:${nacos.port}
demo:
  service:
    version: 1.0.0
    name: demo-server2
server:
  port: 8082