server:
  port: 9090
spring:
  application:
    name: demo-consumer
nacos:
  host: autopai-cloud-nacos-local
  port: 8848
dubbo:
  application:
    name: demo-consumer
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://${nacos.host}:${nacos.port}
demo:
  service:
    version: 1.0.0
    name: demo-server3
